version: "2.1"
services:
  app:
    container_name: delivery-api
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    depends_on:
      delivery-database:
        condition: service_healthy
    ports:
      - "4001:4001"
    volumes:
      - .:/usr/src/app
    links:
    - delivery-database:delivery-database
    networks:
      - app-network
    command: nodemon server.js
  delivery-database:
    image: mongo
    container_name: delivery-database
    restart: always
    command: ["--bind_ip_all"]
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: delivery
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo delivery-database:27017/delivery --quiet
      timeout: 20s
      retries: 10
    ports:
      - '27017-27019:27017-27019'
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
